spring:
  application:
    name: subscriptions
  datasource:
    url: jdbc:h2:mem:subscribersdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
server:
  port: 8081
